import type { AppState, Submission } from "./store";
import type { TrackMeta } from "@/data/tracks";
import { computeTiming, hourLabel } from "./timing";

export type ReportScope = "day" | "week" | "all";

export const SCOPES: { id: ReportScope; label: string; hint: string }[] = [
  { id: "day", label: "Today", hint: "Just the current day" },
  { id: "week", label: "This week", hint: "Last 7 days" },
  { id: "all", label: "Till now", hint: "Day 1 → today" },
];

const fmtDate = (iso: string) => {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? "—"
    : d.toLocaleString("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" });
};

export type ReportInput = {
  state: AppState;
  track: TrackMeta;
  xp: number;
  levelName: string;
  level: number;
  scope: ReportScope;
};

export type Report = {
  heading: string;
  range: [number, number];
  markdown: string;
  linkedin: string;
  filename: string;
  stats: { k: string; v: string }[];
};

export function buildReport({ state, track, xp, levelName, level, scope }: ReportInput): Report {
  const day = Math.min(60, Math.max(1, state.currentDay || 1));
  const from = scope === "day" ? day : scope === "week" ? Math.max(1, day - 6) : 1;
  const to = day;

  const inRange = (d: number) => d >= from && d <= to;
  const completed = state.completedDays.filter(inRange).sort((a, b) => a - b);
  const missed = Array.from({ length: to - from + 1 }, (_, i) => from + i).filter(
    (d) => d < day && !state.completedDays.includes(d),
  );
  const subs: Submission[] = Object.values(state.dailySubmissions).filter((s) => inRange(s.day)).sort((a, b) => a.day - b.day);
  const timing = computeTiming(subs);
  const githubCount = subs.filter((s) => s.github).length;
  const linkedinCount = subs.filter((s) => s.linkedin).length;
  const span = to - from + 1;
  const rate = span > 0 ? Math.round((completed.length / span) * 100) : 0;

  const heading =
    scope === "day" ? `Day ${day} report` : scope === "week" ? `Week report · Day ${from}–${to}` : `Full report · Day 1–${to}`;

  const stats = [
    { k: "Days completed", v: `${completed.length} / ${span}` },
    { k: "Consistency", v: `${rate}%` },
    { k: "Current streak", v: `${state.streak} days` },
    { k: "Best streak", v: `${state.longestStreak} days` },
    { k: "Total XP", v: xp.toLocaleString("en-IN") },
    { k: "Level", v: `${level} · ${levelName}` },
    { k: "GitHub commits", v: String(githubCount) },
    { k: "LinkedIn posts", v: String(linkedinCount) },
    { k: "Coding personality", v: `${timing.emoji} ${timing.title}` },
    { k: "Peak coding hour", v: timing.peakHour === null ? "—" : hourLabel(timing.peakHour) },
  ];

  const lines: string[] = [];
  lines.push(`# ABTalks 60 Days Challenge — ${heading}`);
  lines.push("");
  lines.push(`**Student:** ${state.user?.name ?? "Anonymous"}${state.profile.college ? ` · ${state.profile.college}` : ""}`);
  lines.push(`**Track:** ${track.name} — ${track.tagline}`);
  lines.push(`**Generated:** ${new Date().toLocaleString("en-IN")}`);
  lines.push("");
  lines.push("## Summary");
  for (const s of stats) lines.push(`- **${s.k}:** ${s.v}`);
  lines.push("");
  lines.push(`> ${timing.description}`);
  lines.push("");
  lines.push("## Daily log");
  lines.push("");
  lines.push("| Day | Topic | Status | Submitted | GitHub |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (let d = from; d <= to; d++) {
    const topic = track.days.find((x) => x.day === d)?.topic ?? "—";
    const sub = state.dailySubmissions[d];
    const status = sub ? "✅ Completed" : d < day ? "❌ Missed" : "⏳ In progress";
    lines.push(`| ${d} | ${topic} | ${status} | ${sub ? fmtDate(sub.submittedAt) : "—"} | ${sub?.github ?? "—"} |`);
  }
  if (subs.length) {
    lines.push("");
    lines.push("## Reflections");
    for (const s of subs) {
      if (!s.notes) continue;
      lines.push(`- **Day ${s.day}:** ${s.notes}`);
    }
  }
  lines.push("");
  lines.push("---");
  lines.push("_Generated by ABTalks 60 Days Coding Challenge._");

  const topics = [...new Set(subs.map((s) => track.days.find((x) => x.day === s.day)?.topic).filter(Boolean))].slice(0, 4);
  const scopeLine =
    scope === "day"
      ? `Day ${day} of my #60DaysOfCode challenge is done ✅`
      : scope === "week"
        ? `Week wrap-up: Day ${from} → Day ${to} of my #60DaysOfCode challenge ✅`
        : `${completed.length} days into the 60 Day Coding Challenge and still shipping ✅`;

  const linkedin = [
    scopeLine,
    "",
    `Track: ${track.name}`,
    topics.length ? `What I worked on:\n${topics.map((t) => `• ${t}`).join("\n")}` : "",
    "",
    `📊 Progress so far`,
    `• Days completed: ${state.completedDays.length}/60`,
    `• Current streak: ${state.streak} days 🔥`,
    `• XP earned: ${xp.toLocaleString("en-IN")} (Level ${level} · ${levelName})`,
    `• Consistency in this period: ${rate}%`,
    timing.total ? `• My coding personality: ${timing.emoji} ${timing.title}` : "",
    "",
    "The lesson is boring but true: showing up daily beats studying in bursts.",
    "",
    "If you're a student sitting on tutorials, pick one track and start Day 1 today.",
    "",
    "#60DaysOfCode #ABTalks #Consistency #LearningInPublic #" + track.name.replace(/[^a-zA-Z]/g, ""),
  ]
    .filter((l) => l !== "")
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");

  const filename = `abtalks-${scope}-report-day-${to}.md`;

  return { heading, range: [from, to], markdown: lines.join("\n"), linkedin, filename, stats };
}
